apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-conf
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels" $ | nindent 4 }}
data:
  nginx.conf: |
    server {
    listen       8000;
    server_name  localhost;

    location / {
        root   /homework;
        index  index.html index.htm;
    }
    }