apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "labels" $ | nindent 4 }}
  name: {{ .Release.Name }}-nginx-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: {{ .Values.sourcePort }}
    protocol: TCP
    targetPort: {{ .Values.targetPort }}
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}-nginx