apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: homework
data:
  nginx.conf: |
    server {
    listen       8000;
    server_name  localhost;

    location / {
        root   /homework;
        index  index.html index.htm;
    }
    }

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: homework
spec:
  containers:
  - name: nginx
    image: nginx
    lifecycle:
      preStop:
        exec:
          command: ["/bin/sh", "-c", "rm -f /init/index.html"]
    volumeMounts:
    - name: app
      mountPath: /homework
    - name: nginx-config
      mountPath: /etc/nginx/conf.d/default.conf
      subPath: nginx.conf
  initContainers:
  - name: init
    image: busybox:1.31
    command: ['/bin/sh', '-c', 'echo \<h1\>Hello World\</h1\> > /init/index.html']
    volumeMounts:
    - name: app
      mountPath: /init
  volumes:
  - name: app
    emptyDir: {}
  - name: nginx-config
    configMap:
      name: nginx-config